// Keep one shared Wrangler configuration; inject only account-specific values.
import { accessSettings } from '../crates/worker/access.mjs';
export function productionConfig(base, env) {
  const access = accessSettings(env);
  const account = env.CLOUDFLARE_ACCOUNT_ID?.trim() ?? '';
  const database = env.FOLIO_D1_DATABASE_ID?.trim() ?? '';
  const domain = env.FOLIO_DOMAIN?.trim().toLowerCase() ?? '';
  const region = env.FOLIO_PLACEMENT_REGION?.trim() ?? '';
  if (region && !/^(aws|gcp|azure):[a-z0-9-]+$/.test(region)) {
    throw new Error('FOLIO_PLACEMENT_REGION must be a Cloudflare-supported provider:region placement hint.');
  }
  if (!/^[a-f0-9]{32}$/i.test(account) || /^0+$/.test(account)) {
    throw new Error('CLOUDFLARE_ACCOUNT_ID must be your 32-character Cloudflare account ID.');
  }
  if (!/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i.test(database) || database === '00000000-0000-0000-0000-000000000000') {
    throw new Error('FOLIO_D1_DATABASE_ID must be the real D1 database UUID.');
  }
  const labels = domain.split('.');
  if (domain.length > 253 || labels.length < 2 || labels.some(label => !/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(label)) ||
      /(^|\.)(example\.(com|net|org)|invalid|test|localhost|local)$/.test(domain) || !/[a-z]/.test(labels.at(-1))) {
    throw new Error('FOLIO_DOMAIN must be your DNS hostname, without https://, a path, or a wildcard.');
  }
  const placeholder = 'database_id = "00000000-0000-0000-0000-000000000000"';
  if (base.split(placeholder).length !== 2 || base.split('FOLIO_AUTH_METHOD = "password"').length !== 2 || !/^workers_dev = false$/m.test(base.replaceAll('\r', '')) ||
      /^account_id\s*=|^routes\s*=|^\[limits\]/m.test(base)) {
    throw new Error('Shared wrangler.toml changed; review production configuration generation.');
  }
  return `# Generated by npm run worker:configure. Do not commit.\n` +
    `account_id = "${account}"\nroutes = [{ pattern = "${domain}", custom_domain = true }]\n\n` +
    base.replace('[placement]\nmode = "smart"', region ? `[placement]\nregion = "${region}"` : '[placement]\nmode = "smart"')
      .replace(placeholder, `database_id = "${database}"`)
      .replace('# Replace this local placeholder with the production D1 database ID.\n', '')
      .replace('# Local emulation only. Production generator replaces this with cloudflare_access.', '# Cloudflare Access is required; no password fallback.')
      .replace('FOLIO_AUTH_METHOD = "password"', `FOLIO_AUTH_METHOD = "cloudflare_access"\nFOLIO_ACCESS_TEAM_DOMAIN = ${JSON.stringify(new URL(access.issuer).hostname)}\nFOLIO_ACCESS_AUD = ${JSON.stringify(access.audience)}\nFOLIO_ACCESS_EMAIL = ${JSON.stringify(access.emails.join(','))}`);
}
