import assert from 'node:assert/strict';
const base = process.argv[2] || 'http://127.0.0.1:8788';
if (!/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(base)) throw new Error('Smoke tests require a disposable loopback server.');
let cookie = '', csrf = '';
const noteId='smoke-note-'+Date.now();
async function call(method,path,body,expected=200,extra={}) {
 const response=await fetch(base+path,{method,signal:AbortSignal.timeout(30_000),headers:{'content-type':'application/json',cookie,'x-csrf-token':csrf,...extra},body:method==='GET'?undefined:JSON.stringify(body??{})});
 const data=await response.json();
 assert.equal(response.status,expected,method+' '+path+': '+JSON.stringify(data));
 if(response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];
 return data;
}
await call('GET','/api/health');
await call('GET','/api/notes',null,401);
const status=await call('GET','/api/auth/status');
const auth=await call('POST',status.setup_required?'/api/auth/setup':'/api/auth/login',{username:'folio-test',password:'Folio-local-test-2026!'},200,{'x-setup-token':'folio-local-worker-verification-token'});
csrf=auth.csrf;
assert.ok(csrf);
await call('POST','/api/tasks',{title:'blocked'},403,{'x-csrf-token':'incorrect'});
await call('POST','/api/tasks',{title:'blocked'},403,{origin:'https://other.example'});
await call('PUT','/api/notes/invalid.id',{markdown:'bad'},400);
await call('PUT','/api/notes/oversized',{markdown:'x'.repeat(128*1024+1)},400);
let note=await call('PUT','/api/notes/'+noteId,{markdown:'# A quiet plan\n\n- [ ] Finish the first chapter @due(2026-09-15)\n- [x] Make room to think\n',folder:'Projects/Reading'});
const tasks=await call('GET','/api/tasks');
const task=tasks.items.find(t=>t.source_note_id===noteId&&!t.completed);
assert.ok(task);
await call('PUT','/api/tasks/'+task.id,{completed:true,due_date:'2026-09-16',due_time:'09:30'});
const changed=await call('GET','/api/notes/'+noteId);
assert.match(changed.markdown,/- \[x\] Finish the first chapter @due\(2026-09-16\) @time\(09:30\)/);
await call('PUT','/api/notes/'+noteId,{markdown:'stale draft',folder:'Projects/Reading',revision:note.revision},409);
const search=await call('GET','/api/notes?q=chapter');
assert.ok(search.items.some(n=>n.id===noteId));
await call('DELETE','/api/folders',{path:'Projects/Reading'},409);
await call('POST','/api/folders',{path:'Personal/Empty'});
await call('DELETE','/api/folders',{path:'Personal/Empty'});
await call('POST','/api/tasks',{title:'Invalid calendar day',due_date:'2026-02-30'},400);
const goal=await call('POST','/api/goals',{title:'Read with intention',description:'A few pages, a little attention, every day.',position:1});
await call('PUT','/api/goals/'+goal.id,{status:'completed'});
await call('PUT','/api/goals/'+goal.id,{status:'active',position:0});
const temp=await call('PUT','/api/notes/smoke-delete',{markdown:'# Temporary test',folder:'Personal'});
await call('DELETE','/api/notes/smoke-delete',{revision:temp.revision});
await call('GET','/api/notes/smoke-delete',null,404);
const archived=await call('PUT','/api/notes/'+noteId,{...changed,folder:'Archive'});
assert.equal(archived.archived,true);
assert.ok(!(await call('GET','/api/notes')).items.some(n=>n.id===noteId));
assert.ok((await call('GET','/api/notes?folder=Archive')).items.some(n=>n.id===noteId));
await call('PUT','/api/notes/'+noteId,{markdown:changed.markdown,folder:'Projects/Reading',revision:archived.revision});
await call('POST','/api/tasks',{title:'Make time for a walk',due_date:'2026-09-15',due_time:'17:00'});
await call('POST','/api/tasks',{title:'A small idea for another day'});
const workspace=await call('GET','/api/workspace');
assert.ok(workspace.notes.items.length);
const root='Folder-check-'+Date.now();
await call('POST','/api/folders',{path:root+'/Child/Empty'});
await call('POST','/api/folders',{path:root+'/Child'},409);
const folderNotes=[];
for(let i=0;i<3;i++) {
 const id=noteId+'-tree-'+i;
 const folder=i===0?root:root+'/Child';
 const saved=await call('PUT','/api/notes/'+id,{markdown:'# Tree file '+i+'\n\n- [ ] Preserve this task',folder});
 folderNotes.push(saved);
}
const direct=await call('GET','/api/notes?folder='+encodeURIComponent(root)+'&exact=true');
assert.equal(direct.items.length,1);
let renamed=await call('PUT','/api/folders',{path:root,name:root+' renamed'});
assert.equal(renamed.done,false);
assert.equal((await call('GET','/api/folders/rename')).source,root);
await call('POST','/api/folders',{path:root+'/Blocked'},409);
await call('DELETE','/api/folders',{path:root},409);
renamed=await call('PUT','/api/folders',{path:root,name:root+' renamed'});
assert.equal(renamed.done,true);
assert.equal(await call('GET','/api/folders/rename'),null);
for(const n of folderNotes){
 const read=await call('GET','/api/notes/'+n.id);
 assert.equal(read.folder,n.folder.replace(root,root+' renamed'));
 assert.match(read.markdown,/Preserve this task/);
 await call('DELETE','/api/notes/'+n.id,{revision:read.revision});
}
const folders=await call('GET','/api/folders');
assert.ok(folders.some(f=>f.path===root+' renamed/Child/Empty'));
assert.ok(!folders.some(f=>f.path===root));
await call('DELETE','/api/folders',{path:root+' renamed'});
await call('POST','/api/auth/logout');
await call('GET','/api/notes',null,401);
console.log('PASS: session auth, CSRF, origin, validation, notes, search, checkbox synchronization, conflict, nested folders, resumable rename, archive, delete, goals, tasks and logout.');
