import {escape,icon,button,layout,sectionHeading,taskRow,taskForm,noteRow,goalCard} from './components.mjs';
import {markdown} from './markdown.mjs';
export const dateKey=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
export const parseDate=s=>new Date(`${s}T12:00:00`);
const heading=(eyebrow,title,description='')=>`<header class="page-heading"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1>${description?`<p>${description}</p>`:''}</header>`;
const empty=text=>`<p class="empty">${text}</p>`;
export function home(state,now=new Date()) {
  const today=dateKey(now),tasks=state.tasks.filter(t=>t.date===today),greeting=now.getHours()<12?'Good morning.':now.getHours()<18?'Good afternoon.':'Good evening.';
  return layout({title:'Home',content:`<div class="date-strip"><span class="eyebrow">● &nbsp; ${now.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</span><span class="meta">A fresh page, a little possibility.</span></div><header class="greeting"><div><h1>${greeting}</h1><p>Make room for what matters.</p></div><a class="text-link" href="/daily">Open today's note ${icon('arrow')}</a></header><section class="section">${sectionHeading('<span class="eyebrow">What matters · Long-term goals</span>','<a class="text-link" href="/goals/new">＋ Add goal</a>')}<div class="goals">${state.goals.filter(g=>g.status==='active').map(goalCard).join('')||empty('Give your days a direction.')}</div></section><section class="section">${sectionHeading("Today's intentions",`<span class="meta">${tasks.filter(t=>t.completed).length} of ${tasks.length} complete</span>`)}<div class="ruled-list">${tasks.map(t=>taskRow(t,'/')).join('')||empty('A little breathing room. What will you focus on?')}${taskForm(today,'/')}</div></section><section class="section quick-note" id="quick-note">${sectionHeading('Quick note','<span class="meta">A thought worth keeping.</span>')}<form action="/notes/quick" method="post"><textarea name="body" aria-label="Quick note" placeholder="Let a thought land here…" required maxlength="100000"></textarea><div class="quick-footer"><span class="meta">Saved as a new note in Personal</span><button class="button primary">Create note ${icon('arrow')}</button></div></form></section><section class="section">${sectionHeading('Recently edited', '<a class="text-link" href="/notes">All notes ↗</a>')}<div class="recent-notes">${[...state.notes].filter(n=>n.notebook!=='Archive').sort((a,b)=>b.updated.localeCompare(a.updated)).slice(0,4).map(noteRow).join('')||empty('Your notes will find a home here.')}</div></section><footer class="footer-note"><span><kbd>⌘ K</kbd> Find a note</span><span><kbd>⌘ N</kbd> New note</span><span><kbd>⌘ S</kbd> Save</span></footer>`});
}
export function todo(state,url) {
 const group=url.searchParams.get('group')||'Today',today=dateKey(),groups=['Today','Upcoming','Someday','Completed'];
 const filters={Today:t=>!t.completed&&t.date&&t.date<=today,Upcoming:t=>!t.completed&&t.date>today,Someday:t=>!t.completed&&!t.date,Completed:t=>t.completed};
 const selected=groups.includes(group)?group:'Today',returnTo=`/todo?group=${selected}`,tasks=state.tasks.filter(filters[selected]);
 return layout({active:'todo',title:'Todo',content:heading('One thing at a time','Tasks & intentions','A place for everything on your mind. A little less to carry.')+`<nav class="tabs" aria-label="Task groups">${groups.map(g=>`<a class="${g===selected?'active':''}" href="/todo?group=${g}" ${g===selected?'aria-current="page"':''}>${g} <span class="meta">${state.tasks.filter(filters[g]).length}</span></a>`).join('')}</nav><section>${sectionHeading(selected,`<span class="meta">${tasks.length} intentions</span>`)}<div class="ruled-list">${tasks.map(t=>taskRow(t,returnTo)).join('')||empty('Nothing here for now. Enjoy the space.')}${selected!=='Completed'?taskForm(selected==='Someday'?'':today,returnTo):''}</div></section>`});
}
export function planner(state,url) {
 const raw=url.searchParams.get('date'),chosen=raw&&/^\d{4}-\d{2}-\d{2}$/.test(raw)&&!isNaN(parseDate(raw))?parseDate(raw):new Date(),daily=url.searchParams.get('view')==='daily';
 const start=new Date(chosen);if(!daily)start.setDate(start.getDate()-((start.getDay()+6)%7));
 const days=Array.from({length:daily?1:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d;});
 const end=days.at(-1),prev=new Date(start),next=new Date(start);prev.setDate(prev.getDate()-(daily?1:7));next.setDate(next.getDate()+(daily?1:7));
 const link=d=>`/planner?date=${dateKey(d)}&view=${daily?'daily':'weekly'}`;
 return layout({active:'planner',title:'Planner',content:heading('A little perspective',daily?'Your daily page.':'The weekly horizon.','Give your intentions a place in the week.')+`<div class="planner-toolbar"><div class="date-navigation">${button('‹',link(prev))}<span class="meta">${start.toLocaleDateString('en-US',{month:'long',day:'numeric'})}${daily?'':` – ${end.toLocaleDateString('en-US',{month:'short',day:'numeric'})}`}, ${start.getFullYear()}</span>${button('›',link(next))}${button('Today','/planner?view='+(daily?'daily':'weekly'))}</div><div class="segmented"><a class="${daily?'active':''}" href="/planner?date=${dateKey(chosen)}&view=daily">Daily</a><a class="${daily?'':'active'}" href="/planner?date=${dateKey(chosen)}&view=weekly">Weekly</a></div></div>${daily?`<div class="ruled-list">${state.tasks.filter(t=>t.date===dateKey(chosen)).map(t=>taskRow(t,link(chosen))).join('')||empty('Start with one small intention.')}${taskForm(dateKey(chosen),link(chosen))}</div>`:`<div class="week">${days.map(d=>`<section class="day ${dateKey(d)===dateKey()?'current':''}"><header class="day-header"><span>${d.toLocaleDateString('en-US',{weekday:'short'}).toUpperCase()}</span><strong>${d.getDate()}</strong></header>${state.tasks.filter(t=>t.date===dateKey(d)).map(t=>taskRow(t,link(chosen))).join('')}<a class="day-add" href="/planner?view=daily&date=${dateKey(d)}">＋ Add intention</a></section>`).join('')}</div>`}<section class="section" style="margin-top:32px">${sectionHeading('Not yet scheduled','<a class="text-link" href="/todo?group=Someday">View someday ↗</a>')}<div class="ruled-list">${state.tasks.filter(t=>!t.date&&!t.completed).slice(0,3).map(t=>taskRow(t,link(chosen))).join('')||empty('Everything has its place.')}</div></section>`});
}
export function notes(state,url) {
 const q=url.searchParams.get('q')||'',notebook=url.searchParams.get('notebook')||'',filtered=[...state.notes].filter(n=>(notebook?n.notebook===notebook:n.notebook!=='Archive')&&`${n.title} ${n.body}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>b.updated.localeCompare(a.updated));
 const selected=state.notes.find(n=>n.id===url.searchParams.get('id'))||filtered[0],preview=url.searchParams.get('mode')==='preview';
 const content=`<aside class="note-browser"><div class="note-browser-header"><h2>${escape(notebook||'All notes')}</h2><form method="get" action="/notes"><input class="note-filter" type="search" name="q" aria-label="Filter notes" placeholder="Search these pages…" value="${escape(q)}">${notebook?`<input type="hidden" name="notebook" value="${escape(notebook)}">`:''}<button class="text-button">Search</button></form><span class="meta">${filtered.length} pages</span></div>${filtered.map(n=>noteRow(n).replace('class="note-row"',`class="note-row ${n.id===selected?.id?'selected':''}"`)).join('')||empty('No matching notes.')}</aside>${selected?`<article class="editor"><form id="editor-form" method="post" action="/notes/${escape(selected.id)}/save"><div class="editor-toolbar"><span class="meta">${escape(selected.notebook)} / ${escape(selected.title)}.md</span><div class="segmented"><a class="${!preview?'active':''}" href="/notes?id=${escape(selected.id)}">Edit</a><a class="${preview?'active':''}" href="/notes?id=${escape(selected.id)}&mode=preview">Preview</a></div></div><input class="editor-title" name="title" aria-label="Note title" value="${escape(selected.title)}" required maxlength="240"><div class="editor-metadata"><label>Folder <select name="notebook" aria-label="Move to folder">${['Daily','Projects','Personal','Archive'].map(n=>`<option ${n===selected.notebook?'selected':''}>${n}</option>`).join('')}</select></label><span>Edited ${escape(new Date(selected.updated).toLocaleDateString('en-US',{month:'short',day:'numeric'}))}</span><span id="save-status" role="status" aria-live="polite">Saved locally</span></div>${preview?`<div class="editor-preview">${markdown(selected.body)}</div><textarea hidden name="body">${escape(selected.body)}</textarea>`:`<textarea class="editor-body" name="body" aria-label="Markdown editor" spellcheck="false">${escape(selected.body)}</textarea>`}<footer class="editor-footer"><span class="meta" id="word-count">${selected.body.trim().split(/\s+/).filter(Boolean).length} words · Markdown</span><button class="text-button" type="submit">Save <kbd>⌘ S</kbd></button></footer></form></article>`:empty('A blank page is a good beginning. Create a new note to get started.')}`;
 return layout({active:'notes',title:'Notes',content});
}
export function goalForm(){return layout({title:'New goal',content:heading('What matters','A direction worth following.')+`<form class="form-grid" method="post" action="/goals"><label>Goal<input name="title" required maxlength="240" placeholder="What would you like to work toward?"></label><label>A little more about it<textarea name="description" rows="4" maxlength="2000"></textarea></label><div><button class="button primary">Add goal</button> ${button('Cancel','/')}</div></form>`});}
export function settings(){return layout({title:'Settings',content:heading('Your own quiet corner','Workspace settings.')+`<section><div class="settings-row"><div><h3>Appearance</h3><p>Light paper or a warm dark canvas. Your choice stays on this browser.</p></div><button class="button" data-theme-toggle aria-label="Switch to dark mode"><span data-theme-label>Dark mode</span></button></div><div class="settings-row"><div><h3>UI preview</h3><p>This is a local design preview. Changes are saved on this computer.</p></div><span class="meta">No cloud connection</span></div><div class="settings-row"><div><h3>Markdown is yours.</h3><p>Download your notes as a JSON bundle containing their original Markdown.</p></div>${button('Export notes','/export')}</div><div class="settings-row"><div><h3>Paper & Folio</h3><p>Shared colors, typography, and reusable interface components.</p></div>${button('View design system','/design-system')}</div><div class="settings-row"><div><h3>Cloud storage</h3><p>The planned Rust Worker will use R2 for Markdown and D1 for indexes. Authentication and cloud storage are not connected in this UI preview.</p></div></div></section>`});}
export function designSystem(state){const colors={Paper:'#fcf9f8',Sheet:'#ffffff',Well:'#f6f3f2',Ink:'#242424',Muted:'#716e68',Line:'#e5dfda',Sage:'#476552',Terracotta:'#8c4a2f'};return layout({title:'Design system',content:heading('Paper & Folio · 01','A shared visual language.','Extracted from Stitch. Shaped for a quiet, personal planner.')+`<section class="section">${sectionHeading('Foundations')}<div class="swatches">${Object.entries(colors).map(([name,color])=>`<div class="swatch"><div class="swatch-color" style="--swatch:${color}"></div><p>${name}<br>${color}</p></div>`).join('')}</div></section><section class="section">${sectionHeading('Typography')}<div class="specimen"><div class="eyebrow">Newsreader · Editorial headings</div><h1>Room to think.</h1><h2 style="margin-top:12px">A thought worth keeping.</h2></div><div class="specimen"><div class="eyebrow">Geist · Interface & prose</div><p style="color:var(--ink)">Make room for what matters. Calm, readable copy at a comfortable pace.</p></div><div class="specimen"><div class="eyebrow">JetBrains Mono · Metadata</div><span class="meta">MONDAY, SEPTEMBER 14 · SAVED LOCALLY · 240 WORDS</span></div></section><section class="section">${sectionHeading('Common components')}<div class="specimen"><div class="eyebrow">Action / Primary · Secondary · Text</div><div class="component-actions">${button('Create note','#','primary')}${button('Cancel','#')}<a class="text-link" href="#">All notes ↗</a><button class="button" disabled>Saving…</button></div></div><div class="specimen"><div class="eyebrow">Task / Open · Complete · Add</div>${taskRow({...state.tasks[0],id:'specimen-open'},'/design-system')}${taskRow({...state.tasks[0],id:'specimen-done',completed:true},'/design-system')}${taskForm(dateKey(),'/design-system')}</div><div class="specimen"><div class="eyebrow">Content / Goal · Note</div><div class="goals">${goalCard(state.goals[0],0)}</div><div style="margin-top:16px">${noteRow(state.notes[0])}</div></div><div class="specimen"><div class="eyebrow">Spacing & geometry</div><p>4 · 8 · 12 · 16 · 24 · 32 · 40 · 48 px</p><p>4 px controls · 6 px containers · 8 px dialogs · 1 px borders</p></div></section>`});}
